config/routes.rb
Rails.application.routes.draw do
  # devise_for :users # this was before modification about quizzes stay after user deleted
  devise_for :users, controllers: { # user now can be deleted quizzes stays?
    registrations: 'users/registrations'
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  get '/', to: redirect('/quizzes')

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home', to: 'home#index'

  resources :quiz_statistics, only: [:index, :create]

  resources :quizzes do
    resources :questions, except: [:index]

    member do
      get 'take', to: 'quiz_taking#take'
      post 'submit', to: 'quiz_taking#submit'
      get 'results', to: 'quiz_taking#results'
    end
  end

  get 'quizzes/:id/results', to: 'quiz_taking#results', as: 'quiz_results'
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authorize_user, except: [:index, :show]
  before_action :load_quiz, except: [:index, :create, :new]

  def index
    @quizzes = Quiz.all
  end

  def show
  end

  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = current_user.quizzes.new(quiz_params)

    if @quiz.save
      redirect_to @quiz, notice: 'Hooray! You did it!'
    else
      flash.now.alert = 'Sorry, something went wrong..'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if params[:add_question]
      @quiz.assign_attributes(quiz_params)
      @quiz.questions.build
      render :edit, status: :ok
    elsif @quiz.update(quiz_params)
      @quiz.image.purge if params.dig(:quiz, :remove_image) == '1'
      update_answers
      redirect_to @quiz
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quiz.destroy
    redirect_to quizzes_path
  end

  def questions
    render json: @quiz.questions
  end

  private

  def load_quiz
    @quiz = Quiz.find(params[:id])
  end

  def authorize_user
    authorize! :manage, Quiz
  end

  def quiz_params
    params.require(:quiz).permit(
      :title,
      :description,
      :image,
      questions_attributes: [
        :id,
        :content,
        :answer,
        :question_type,
        :_destroy,
        answers_attributes: [:id, :choice, :correct, :_destroy]
      ]
    )
  end

  def update_answers
    @quiz.questions.each do |question|
      next unless question.question_type == 'Multiple Choice'

      question.answers.each do |answer|
        answer_params = params.dig(:quiz, :questions_attributes, question.id.to_s, :answers_attributes, answer.id.to_s)
        answer.update(answer_params) if answer_params
      end
    end
  end
end

app/views/quizzes/_form.html.slim
- quiz.errors.full_messages.each do |error|
  p style="color: rgba(0, 204, 255)"
    = error
= form_with(model: quiz) do |form|
  = form.label :title, 'Title', class: 'form-label'
  = form.text_field :title, class: 'form-style'
  = form.label :description, 'Description', class: 'form-label'
  = form.text_area :description, class: 'form-style'

  = form.label :image, 'Image', class: 'form-label'
  br
  = form.file_field :image, class: 'custom-file-input'
  - if quiz.image.attached?
    .d-flex.align-items-center
      = form.check_box :remove_image, value: '1', class: 'custom-checkbox'
      = form.label :remove_image, 'Remove Image', class: 'custom-checkbox-label'

  h3 Questions
  = form.fields_for :questions do |q_form|
    fieldset
      = q_form.label :content, 'Content', class: 'form-label'
      = q_form.text_field :content, class: 'form-style'
      - if q_form.object.question_type == 'Single Answer'
        = q_form.label :answer, 'Answer', class: 'form-label'
        = q_form.text_field :answer, class: 'form-style'
      - elsif q_form.object.question_type == 'Multiple Choice'
        = q_form.fields_for :answers, q_form.object.answers do |a_form|
          .answer-fieldset
            = a_form.label :choice, 'Choice', class: 'form-label'
            = a_form.text_field :choice, class: 'form-style'
            = a_form.check_box :correct, class: 'custom-checkbox'
            = a_form.label :correct, 'Correct', class: 'custom-checkbox-label'
            = a_form.hidden_field :id

      = q_form.check_box :_destroy, class: 'custom-checkbox'
      = q_form.label :_destroy, 'Remove Question', class: 'custom-checkbox-label'

  - if current_user || (current_user.id == @quiz.user_id || current_user.is_admin)
    div
      = form.submit 'Update Quiz', class: 'custom-button'

app/views/quizzes/edit.html.slim
div.content-container
    h1 Edit Quiz

    = render 'form', quiz: @quiz

    = button_to 'Back to Quiz', quiz_path(@quiz), method: :get, class: 'custom-button'

app/views/quizzes/index.html.slim
h1.index-title Group4 Quizzes
h2.index-description Welcome to Group4 Quizzes, your one-stop destination for knowledge exploration. Immerse yourself in a world of interactive quizzes spanning an array of subjects. Challenge your intellect, learn something new, and have fun along the way! Feel free to pick and choose and quiz you want to play, or create one yourself!

table.styled-table
  thead
    tr
      th Title
      th Created At
      th Question Count
      th Description
      th Choose
      th Creator
  tbody
    - @quizzes.each do |quiz|
      tr
        //td = quiz.id
        td = link_to quiz.title, quiz_path(quiz), class: 'styled-link'
        td = date_in_words(quiz.created_at)
        td = quiz.question_count
        td = quiz.description
        - if quiz.question_count > 0
          td = button_to "Take Quiz", take_quiz_path(quiz), method: :get, class: 'custom-button-table'
        - else
          td = "Take Quiz"
        - if quiz.user_id.present?
          td= "#{quiz.creator.first_name}, #{quiz.creator.last_name}"
        - else
          td= "DELETED USER"

- if current_user
  = button_to 'Create Quiz', new_quiz_path, method: :get, class: 'custom-button'

app/views/quizzes/new.html.slim
div.content-container
    h1 New Quiz

    = render 'form', quiz: @quiz

    = button_to 'Back to Quizzes', quizzes_path, method: :get, class: 'custom-button'

app/views/quizzes/show.html.slim
div.content-container
  h1 = @quiz.title
  div.created
    span Quiz created at: 
    span = @quiz.created_at.strftime('%Y/%m/%d')

    - if @quiz.creator.present?
      p
        | Quiz created by: 
        = @quiz.creator.first_name
        = ' '
        = @quiz.creator.last_name

  div
    p = @quiz.description
    - if @quiz.image.attached?
      = image_tag @quiz.image, style: 'border: 2px solid #FF00AA;'

  h3 Questions
  ul
    - @quiz.questions.each do |q|
      li = link_to q.content, quiz_question_path(@quiz, q), class: 'styled-link'

  .button-container
    - if current_user && (current_user.id == @quiz.user_id || current_user.is_admin)
      = button_to 'Add Question', new_quiz_question_path(@quiz), method: :get, class: 'custom-button'
      = button_to 'Edit Quiz', edit_quiz_path(@quiz), method: :get, class: 'custom-button'
      = button_to "Destroy Quiz", @quiz, method: :delete, class: 'custom-button'
      = button_to 'Back Quizzes', quizzes_path, method: :get, class: 'custom-button'
    - else
      = button_to 'Back Quizzes', quizzes_path, method: :get, class: 'custom-button'