config/routes.rb
Rails.application.routes.draw do
  # devise_for :users # this was before modification about quizzes stay after user deleted
  devise_for :users, controllers: { # user now can be deleted quizzes stays?
    registrations: 'users/registrations'
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  get '/', to: redirect('/quizzes')

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home', to: 'home#index'

  resources :quiz_statistics, only: [:index, :create]

  resources :quizzes do
    resources :questions, except: [:index]

    member do
      get 'take', to: 'quiz_taking#take'
      post 'submit', to: 'quiz_taking#submit'
      get 'results', to: 'quiz_taking#results'
    end
  end

  get 'quizzes/:id/results', to: 'quiz_taking#results', as: 'quiz_results'
end

app/views/shared/_flash.html.slim
 - if flash.any?
   - flash.each do |type, msg|
     div.alert(class=type)
       p = msg

app/views/shared/_footer.html.slim
footer(style="margin-top: 5em; text-align: center;")
  hr(style="border: none; height: 1px; background-color: #333; width: 100%; margin: 0 auto; margin-bottom: 20px;")
  p
    | © 2023 Group4 Quizzes. All Rights Reserved.

app/views/shared/_login_status_message.html.slim
div.login-container
   - if user_signed_in?
     h3 Welcome, #{current_user.first_name} #{current_user.last_name}!
     div(class="#{current_user.is_admin ? 'admin-welcome' : 'user-welcome'}")
       = current_user.is_admin ? "ADMIN" : "USER"
     p #{current_user.email}
     = link_to 'Edit Profile', edit_user_registration_path, class: 'styled-link'
     br
     - if user_signed_in?
       = link_to 'View Quiz Statistics', quiz_statistics_path, class: 'styled-link'
       br
       = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'styled-link'
       br
       = link_to 'Back to Index', quizzes_path, class: 'styled-link'
   - else
     p Please log in to become Admin or Guest.
     = link_to 'Log in', new_user_session_path, class: 'styled-link'
     br
     = link_to 'Back to Index', quizzes_path, class: 'styled-link'