config/routes.rb
Rails.application.routes.draw do
  # devise_for :users # this was before modification about quizzes stay after user deleted
  devise_for :users, controllers: { # user now can be deleted quizzes stays?
    registrations: 'users/registrations'
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  get '/', to: redirect('/quizzes')

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home', to: 'home#index'

  resources :quiz_statistics, only: [:index, :create]

  resources :quizzes do
    resources :questions, except: [:index]

    member do
      get 'take', to: 'quiz_taking#take'
      post 'submit', to: 'quiz_taking#submit'
      get 'results', to: 'quiz_taking#results'
    end
  end

  get 'quizzes/:id/results', to: 'quiz_taking#results', as: 'quiz_results'
end

app/controllers/quiz_taking_controller.rb
User
class QuizTakingController < ApplicationController
  before_action :load_quiz_and_questions, only: %i[take submit]

  def take
    @current_question = @questions[@current_question_index]
  end

  def new
    @quiz_statistic = QuizStatistic.new
  end

  def submit
    user_answer = params[:user_answer]

    if @current_question.question_type == 'Multiple Choice'
      selected_answers = Array(user_answer).reject(&:blank?)

      if selected_answers.empty?
        flash[:alert] = 'Please choose at least one answer before submitting.'
        redirect_to take_quiz_path(@quiz, current_question_index: @current_question_index)
        return
      else
        correct_answers = @current_question.answers.select(&:correct?).pluck
      end
    elsif @current_question.question_type == 'Single Answer'
      if user_answer.blank?
        flash[:alert] = 'Please enter an answer before submitting.'
        redirect_to take_quiz_path(@quiz, current_question_index: @current_question_index)
        return
      else
        correct_answer = @current_question.answers.find_by(correct: true)&.choice
      end
    end
    save_user_answer(@current_question, user_answer)
    proceed_to_next_question
  end

  def results
    @quiz = Quiz.find(params[:id])
    @score = session[:quiz_score]
    @results = calculate_score
  end

  private

  def load_quiz_and_questions
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
    @current_question_index = params[:current_question_index].to_i
    @current_question = @questions[@current_question_index]
  end

  def save_user_answer(question, answer)
    session["quiz_#{params[:id]}_user_answers"] ||= {}
    session["quiz_#{params[:id]}_user_answers"]["q#{question.id}_answer"] = answer
  end

  def calculate_score
    user_answers = session["quiz_#{params[:id]}_user_answers"]
    @questions = @quiz.questions
    score = 0
    results = []

    @questions.each do |question|
      user_answer = user_answers["q#{question.id}_answer"]

      if question.question_type == 'Multiple Choice'
        correct_choices = question.answers.select(&:correct?).pluck(:choice)
        user_choices = user_answer.is_a?(Array) ? user_answer : [user_answer]

        if (correct_choices - user_choices).empty? && (user_choices - correct_choices).empty?
          score += 1
          results << { question: question, correct: true }
        else
          results << { question: question, correct: false }
        end
      elsif question.question_type == 'Single Answer'
        if user_answer == question.answer
          score += 1
          results << { question: question, correct: true }
        else
          results << { question: question, correct: false }
        end
      end
    end

    session[:quiz_score] = score
    results
  end

  def proceed_to_next_question
    if @current_question_index == @questions.length - 1
      session[:quiz_score] = calculate_score
      redirect_to quiz_results_path(@quiz)
      if user_signed_in?
        save_quiz_statistic
      end
    else
      redirect_to take_quiz_path(@quiz, current_question_index: @current_question_index + 1)
    end
  end

  def save_quiz_statistic
    #creator_id = @quiz.creator.id if @quiz.creator.id.present?

    quiz_statistic = QuizStatistic.new(
      test_id: @quiz.id,
      creator_id: @quiz.creator&.id,
      correct_answers: results.count { |result| result[:correct] == true },
      total_questions: @questions.length,
      quiz_finisher_id: current_user.id,
      user_id: current_user.id
    )
  
    if quiz_statistic.save
      flash[:alert] = 'Quiz statistic saved successfully!'
    else
      flash[:alert] = "Failed to save quiz statistic"
    end
  end
  
end

app/views/quiz_taking/_form.html.slim
form.form-style action="#{submit_quiz_path(@quiz)}" method="post"
  = csrf_meta_tags

  - @questions.each_with_index do |question, index|
    h3 Question #{index + 1}
    p= question.content
    = text_field_tag "user_answers[q#{question.id}_answer]", nil, placeholder: "Your answer", class: 'form-style'

  = submit_tag "Submit Answers", class: 'custom-button'

app/views/quiz_taking/results.html.slim
.content-container
  h1 Your Quiz Results

  - if @quiz.creator.present?
  p 
    | Quiz created by: 
    - if @quiz.creator.present?
      = @quiz.creator&.first_name
      = @quiz.creator&.last_name
    - else
      = "DELETED USER"

  - if @score.is_a?(Integer)
    h2 Your Score: #{@score}

    ul
      - @results.each do |result|
        li
          h3 = result[:question]["content"]
          - class_name = result[:correct] ? 'correct' : 'incorrect'
          p class="#{class_name}"
            = result[:correct] ? 'Correct! ' : 'Incorrect! '
            - unless result[:correct]
              span class="#{class_name}" Your Answer: 
              span
                - if result[:question]["question_type"] == 'Multiple Choice'
                  - if session["quiz_#{params[:id]}_user_answers"].present?
                    - user_answer = session["quiz_#{params[:id]}_user_answers"]["q#{result[:question]["id"]}_answer"]
                    - unless user_answer.blank?
                        = user_answer.join(', ')
                - else
                  = session["quiz_#{params[:id]}_user_answers"]["q#{result[:question]["id"]}_answer"]
          p
            span class="#{class_name}" Correct Answer: 
            span class="#{class_name}"
              - if result[:question]["question_type"] == 'Multiple Choice'
                - correct_choices = result[:question].answers.select(&:correct?).map(&:choice)
                = correct_choices.join(', ')
              - else
                = result[:question]["answer"]

    p Share your results with others:
    input#results-link type="text" value="#{request.original_url}"
    button#copy-link-button Copy Link

    = button_to 'Back to Quizzes', quizzes_path, method: :get, class: 'custom-button'

  - else
    p Are you ready to see your results?

    = button_to 'View Quiz Results', quiz_results_path(@quiz), method: :get, class: 'custom-button'

app/views/quiz_taking/take.html.slim
.content-container
  - if @current_question.present?
    h3 Question #{@current_question_index + 1}
    p = @current_question.content

    = form_with(url: submit_quiz_path(@quiz), method: :post, remote: true) do |form|
      = csrf_meta_tags
      = form.hidden_field :current_question_index, value: @current_question_index

      - if @current_question.question_type == 'Multiple Choice'
        ul
          - @current_question.answers.each do |answer|
            li
              label.custom-checkbox-label
                = check_box_tag 'user_answer[]', answer.choice, false, class: 'custom-checkbox'
                = answer.choice
      - else
        = form.text_field :user_answer, placeholder: "Your answer", class: 'form-style'

      = form.submit "Submit Answer", class: 'custom-button'

    = button_to 'Back to Quizzes', quizzes_path, method: :get, class: 'custom-button'